name: deeper_network_more_iters
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: EmbeddedModel
  use_args: false
  featurize_plan: false
  max_subtask_timesteps: 15
  baseline: state
  size: small
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
synonyms: 